# Generated by Django 5.0.4 on 2024-04-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textsnippet',
            old_name='tag',
            new_name='tags',
        ),
    ]
